### ISSUE TITLE
Question: Support for Vec of 2 different types

### ISSUE THREAD

**Issue by coltfred** [Nadrieril/pest_consume#10]
Hey, I was trying to work with pest_consume and ran into an issue which I don't see in the examples.

My use case can be boiled down to roughly this:

```
a= {"a"}
b={"b"}
top_rule = { SOI ~ a_or_b ~ EOI }
a_or_b = { (a | b)* }
```

When I write a pest_consume function for `a_or_b` I need to handle the iterator and both of the different types `a` and `b`. What is the recommended way to do this? I assume something like this is done in Dhall, but I couldn't find the input pest file, so it was tough to tell.

I tried something like this:

```
    fn a_or_b_core(input: Node) -> Result<AOrB> {
        Ok(match_nodes!(input.into_children();
        [a(a)] => Either::Left(A),
        [b(b)] =>  Either::Right(B)))
    }

    fn a_or_b(input: Node) -> Result<Query> {
        Ok(match_nodes!(input.into_children();
            [a_or_b_core(either_a_or_b)..] => either_a_or_b.collect(),))
    }

    fn top(input: Node) -> Result<Top> {
        Ok(match_nodes!(input.into_children();
            [a_or_b(a_or_b),EOI(_)] => Top(a_or_b) ,
        ))
    }
```

The error is that the `a_or_b_core` variant wasn't found for enum `Rule`.

Thanks for your help! If there is a different/better way to ask questions, let me know.

**Comment by Nadrieril** [comment]
`match_nodes` doesn't work well when a single rule contains several different choice points. Here you have both repetition and `a | b`. To avoid that the simplest is to the grammar:
```
a= {"a"}
b= {"b"}
top_rule = { SOI ~ a_or_b ~ EOI }
a_or_b_core = { a | b }
a_or_b = { a_or_b_core* }
```
If you really can't modify the grammar then you have use the `pest` API directly for that particular rule. `pest_consume` let syou do that when needed.

**Comment by coltfred** [comment]
@Nadrieril That is the workaround I used, I just wanted to make sure that was the recommended way to get around it.

Thanks so much for your response!
