### ISSUE TITLE
match_nodes not documented

### ISSUE THREAD

**Issue by rbtcollins** [Nadrieril/pest_consume#13]
There is a single example of it in the top level docs, but the macro itself and its contract and capabilities is not directly documented.

More sophisticated use cases such as extracting heterogeneous types have to be done by studying the source or the examples, which is less than friendly.

**Comment by Nadrieril** [comment]
Oh, some update of the documentation system seems to have broken the docs I had for that

**Comment by Nadrieril** [comment]
here you go: https://docs.rs/pest_consume/1.1.1/pest_consume/macro.match_nodes.html :)

**Comment by rbtcollins** [comment]
Sweet thanks!
