### ISSUE TITLE
Allow multiple patterns with the same bindings in the match_nodes! macro

### ISSUE THREAD

**Issue by JustusFluegel** [Nadrieril/pest_consume#15]
Allow the following:

```rs
match_nodes!{input;
    [node_1(_),node_2(a),node3(b)..] | [node_2(a),node_3(b)..] | [node_4(_),node_2(a),node_3(b)..] => todo!()
};
```

which would be equivalent to

```rs
match_nodes!{input;
    [node_1(_),node_2(a),node3(b)..] => todo!(),
    [node_2(a),node_3(b)..] => todo!(),
    [node_4(_),node_2(a),node_3(b)..] => todo!()
};
```

**Comment by Nadrieril** [comment]
I'm sorry, I'm not maintaining this crate anymore. Adding this would require weird control-flow hacks. I would accept a PR that does that if it's well-tested

**Comment by JustusFluegel** [comment]
sure I think I can get around to that some time in the future if that is welcome

**Comment by Nadrieril** [comment]
I've implemented or-patterns on `master`. I did the straightfoward thing of desugaring `p | q => body` to `p => body, q => body`. Let me know if that works for your usecase.

**Comment by JustusFluegel** [comment]
that should be fine :+1:

**Comment by Nadrieril** [comment]
Great!
