### ISSUE TITLE
Support accessing Nodes in `match_nodes!`

### ISSUE THREAD

**Issue by tobz1000** [Nadrieril/pest_consume#3]
Sometimes, I want to access a child node directly, rather than its transformed version, within a parsing function. Currently this means I have to fall back to manually calling `children.next().unwrap()...` for each node, and can't take advantage of the `match_nodes` macro.

It would be cool if we could access the node directly, perhaps by not "wrapping" the binding in the match pattern:

```rust
match_nodes! {
    input.into_chlidren();
    [number(n), string(s), node] => { /* n: usize, s: &str, node: Node */ },
    [number(n), string(s), nodes..] => { /* n: usize, s: &str, node: impl Iterator<Node> */ },
}
```

**Comment by Nadrieril** [comment]
What's the rule that would be matched at the location where you want the node? Can you just make that rule return the node? Something like
```rust
fn that_rule(input: Node) -> Result<Node> {
  Ok(input)
}

fn other_rule(input: Node) -> ... {
  match_nodes! {
    input.into_children();
    [number(n), string(s), that_rule(node)] => { ... },
  }
}
```

**Comment by tobz1000** [comment]
The rules which are being matched are intermediate groupings, which might change if I alter precedence, without meaningfully changing the definition of the rule I'm parsing. (Any of the `*_desc` rules [here](https://gitlab.com/tobz1000/stateful-script/-/blob/master/src/grammar.pest).)

I could also conceivably refactor this as multiple matches of different sub-node types where I don't care about the specific rules in each match, e.g:

```
foo = { (bar | baz | ...) "=>" (bar | baz | ...) }
```

I have an external function to turn any node into a common `Expr` type, which I use in this situation, so it'd be ideal to be able to use

```rust
match_nodes! {
    [a, b] => (node_to_expr(a), node_to_expr(b))
}
```

I'd be happy to have a go at implementing if you think it's worthwhile.

**Comment by Nadrieril** [comment]
I'm not a fan of this `node_to_expr`, it defeats the point of `pest_consume`.
A solution would be to use the (so far undocumented) `alias` feature. The way it works is that you add `#[alias(foo)]` before a rule function definition, like here: https://github.com/Nadrieril/dhall-rust/blob/fcce380d5b4588dc5934bc2e5448d1d981761b50/dhall/src/syntax/text/parser.rs#L676-L681 . Then whenever you match `foo(x)` in `match_nodes!`, this could match either the rule `foo` or any rule aliased to it. Of course all those rules must output the same type. In your case I'd make `atom`, `pair`, `record`, etc. alias to `sum`.
It's still an experimental feature, let me know if you manage to make it work.

**Comment by tobz1000** [comment]
Okay, this is as far as I've gotten. My assumptions might be wrong as I'm doing this through trial and error; please correct me if so.

My grammar includes the rule `expr_top`, which is a union of all rules which can be used as an expression. I can alias functions to this as necessary, and transform their output to an `Expr`, e.g.:

```rust
    fn symbol(input: Node) -> Result<&str, ConsumeError> {
        Ok(input.as_str())
    }
```

becomes:

```rust
    #[alias(expr_top)]
    fn symbol(input: Node) -> Result<Expr, ConsumeError> {
        Ok(Expr::Symbol(input.as_str()))
    }
```

Then, within some functions I can match on `expr_top`:

```rust
#[alias(expr_top)]
fn fn_call(input: Node) -> Result<Expr, ConsumeError> {
    let fn_call = match_nodes! {
        input.into_children();
        // func <- arg
        [expr_top(func), fn_call_l_op(_), expr_top(arg)] => FnCall { func, arg },

        // arg -> func
        [expr_top(arg), fn_call_r_op(_), expr_top(func)] => FnCall { func, arg },
    };

    Ok(Expr::FnCall(Box::new(fn_call)))
}
```

So far, this works great. However, it seems as though, when I alias a rule to `expr_top`, I can no longer match on the rule itself. E.g. this implementation does not work any more:

```rust
    fn bind(input: Node) -> Result<Expr, ConsumeError> {
        Ok(match_nodes! {
            // error: no variant or associated item named `ident` found for enum
            // `parser::AliasedRule` in the current scope
            input.into_children();
            [ident(i)] => { ... }
        })
    }
```

(The actual workaround I would use here is to implement `bind` manually because it's pretty trivial. However I'll assume that, as a user, I would want to implement it in terms of the constituent matched `ident`.)

So I modify `bind` to match on `expr_top`. In this case that seems okay, but this limits the matching logic I can perform (e.g. I might want to match on both an `ident` and `symbol` and perform different actions for both, which is no longer possible).

Since `ident` now returns an expr, I also modify the match accordingly. But it seems as though refutable pattern matches are not supported:

```rust
        // error: refutable pattern in local binding: `Block { .. }`, `Int(_)`,
        // `Str(_)` and 8 more not covered
        Ok(match_nodes! {
            input.into_children();
            [expr_top(Expr::Ident(e))] => Expr::Bind(e)
        })
```

So I have to manually unwrap the expression which I've just wrapped in the `ident` function:

```rust
        Ok(match_nodes! {
            input.into_children();
            [expr_top(e)] => {
                match e {
                    Expr::Ident(e) => Expr::Bind(e),
                    _ => panic!()
                }
            }
        })
```

Having to perform this wrapping/unwrapping may also introduce inefficiencies, if e.g. I need to box a result in order to convert it to an `Expr`, then unbox it for usage within another rule.

> I'm not a fan of this `node_to_expr`, it defeats the point of `pest_consume`.

I disagree - I'm using it to cover transformation use cases which currently (afaict) are not fully supported by the `match_nodes` macro. However, I can still potentially benefit significantly from the automatic iteration and ergonomic matching provided by this crate.

For now, it seems that I must fall back to iterating/matching nodes manually in certain parser functions. Or, if I use my adapted `bind` example above, I introduce other limitations.

You could consider the allowance of matching directly on a node as an "escape hatch", so that a user can still use the `match_nodes` macro for aspects of their grammar which are covered by the available functionality, and easily fall back to their own behaviour when required.

**Comment by Nadrieril** [comment]
> So far, this works great. However, it seems as though, when I alias a rule to `expr_top`, I can no longer match on the rule itself.

Yeah indeed that is the case. I don't remember if that's easy to change.
Would changing that solve your problem ?

> I disagree - I'm using it to cover transformation use cases which currently (afaict) are not fully supported by the `match_nodes` macro. However, I can still potentially benefit significantly from the automatic iteration and ergonomic matching provided by this crate.

Fair, but of course I'd prefer to support those cases with the macro.

> You could consider the allowance of matching directly on a node as an "escape hatch", so that a user can still use the `match_nodes` macro for aspects of their grammar which are covered by the available functionality, and easily fall back to their own behaviour when required.

Conceptually I'm not a fan, but if you really need it I can consider implementing that. What would be the syntax ? Just a bare identifier ? I'm worried that might cause confusion.

**Comment by tobz1000** [comment]
> Yeah indeed that is the case. I don't remember if that's easy to change.
Would changing that solve your problem ?

This would fix part of my problem. However, to avoid the wrapping-and-unwrapping issues I described, I think I would need the ability to choose from multiple parsing functions for the same rule, with different return types. Assuming we don't want multiple functions with the same name, these alternative functions would need to specify their rule some other way; probably an attribute. Perhaps something like:

```rust
// standard parse function invoked by `ident(...)`
fn ident(input: Node) -> Result<&str> { ... }

// parse function invoked by `expr_top`, matching the `ident` rule
#[alias(expr_top)]
#[rule(ident)]
fn ident_as_expr(input: Node) -> Result<Expr> {
    Ok(Expr::Ident(Self::ident(input)?))
}
```

(In fact, doing something like that would prevent the need, in my case, for the same function being invoked by multiple match rules.)

Maybe you would compare the above idea more favourably to my original feature request. I think either one would solve my situation - but I have a hunch that the original request is more flexible for other potential use cases. Can't be sure of course :).

> Conceptually I'm not a fan, but if you really need it I can consider implementing that. What would be the syntax ? Just a bare identifier ? I'm worried that might cause confusion.

To me, a bare identifier sort of makes sense. If we try to abstractly compare `match_nodes` syntax to a Rust `match`, a `my_rule(x)` item might be the equivalent of `MyEnum::variant(x)`. Of course, it's a function call and not a simple unwrap, but to me it still denotes getting at the "inner value" to assign to `x`. And so, logically, a bare identifier is like getting the whole unwrapped value, without checking which variant it is.

A more explicit syntax would be fine too.

**Comment by Nadrieril** [comment]
> I would need the ability to choose from multiple parsing functions for the same rule, with different return types.

Oh I see, indeed that's breaking the main assumption that `pest_consume` relies on.

> ```rust
> // parse function invoked by `expr_top`, matching the `ident` rule
> #[alias(expr_top)]
> #[rule(ident)]
> fn ident_as_expr(input: Node) -> Result<Expr> {
>     Ok(Expr::Ident(Self::ident(input)?))
> }
> ```

Yeah, I think that would be neat. Would be complicated to implement though. I'm happy with your initial idea of matching nodes, you've convinced me of its usefulness.

**Comment by Nadrieril** [comment]
@tobz1000 Could you try my new `raw_nodes` branch? I implemented accessing nodes using just bare identifiers.

**Comment by tobz1000** [comment]
In the middle of testing - will update asap.

**Comment by tobz1000** [comment]
I've converted my parse functions back to inner types, rather than `Expr`, utilising the raw nodes. You can see the diff [here](https://gitlab.com/tobz1000/stateful-script/-/commit/e0c130e079cb4ce6102c52f856689af2508553b3?view=parallel#b407ccdabbb9c9a6a9419b55939c81fad76829bd).

Overall, I prefer how this version reads. **However** I can't figure out how to get my PrecClimber working (line 131), because it relies on the old aliased `expr_node` matcher. Do you have any ideas?

**Comment by Nadrieril** [comment]
I have no clue how to fix your precclimber. You might need to use the pest one by hand sadly.

Here's an alternative idea: in order to get what you wanted earlier, i.e.:
```rust
// standard parse function invoked by `ident(...)`
fn ident(input: Node) -> Result<&str> { ... }

// parse function invoked by `expr_top`, matching the `ident` rule
#[alias(expr_top)]
#[rule(ident)]
fn ident_as_expr(input: Node) -> Result<Expr> {
    Ok(Expr::Ident(Self::ident(input)?))
}
```
an easy solution is to add to your grammar
```
ident_as_expr = { ident }
```
Then in the rest of your grammar you use either `ident_as_expr` or `ident`, depending on the type you'll need. The corresponding method wold just be:
```rust
#[alias(expr_top)]
fn ident_as_expr(input: Node) -> Result<Expr> {
	match_nodes!(input.into_children();
		[ident(id)] => Expr::Ident(id)
	)
}
```

**Comment by tobz1000** [comment]
I figured out my prec climber issue; I simply inserted a non-silent rule into the grammar, which is consumed by `fn_call`, which pest_consume can match against.

> an easy solution is to add to your grammar...

This looks feasible - although it adds yet more dummy rules to the grammar, which might itself become unwieldy. It might be better than my current solution if I end up needing even more ways to parse a rule though!

Thanks for all your help and for implementing this, it's a really useful library.

**Comment by Nadrieril** [comment]
Does my branch solve your problem then?

**Comment by tobz1000** [comment]
Yep :) It might be a little neater with the ability to bind different functions to different aliases for a single rule, but I like how it is currently in terms of both conciseness and understandability. And I no longer have to repeat any parse logic for different rules.

(You can merge & delete the branch whenever you want, I'll just switch over to master.)

**Comment by Nadrieril** [comment]
No need to stay on master, I've released a version :)
