### ISSUE TITLE
`match_nodes!` with optional matches

### ISSUE THREAD

**Issue by vise890** [Nadrieril/pest_consume#9]
Hi there,
I am a total rust/pest/pest_consume noobie here, so I apologise in advance if I am missing something obvious or if this is not the right channel to ask, feel free to close the issue if that is the case, I won't be offended!

So, I have a pest grammar that goes something like this:

```pest
todo = { completion? ~ priority? ~ creation_date? ~ completion_date? ~ token* }
```

.. later on in my `pest_consume::parser` I'd have to do something like:

```rust
#[pest_consume::parser]
impl TodoParser {
    // fn completion()
    // fn priority()
    // fn date()
    // fn creation_date()
    // fn completion_date()
    // fn token()
    // ..
    fn todo(node: Node) -> PestResult<Todo> {
        let mut tb = TodoBuilder::default();
        match_nodes!(node.into_children();
        // 4 choose k, tokens always there since it can be empty
        // 4 choose 4 = 1
        [completion(c), priority(p), creation_date(crd), completion_date(cod), token(tkns)..]
            => unimplemented!()!,
        // 4 choose 3 = 4
        [priority(p), creation_date(crd), completion_date(cod), token(tkns)..]
            => unimplemented!(),
        [completion(c), creation_date(crd), completion_date(cod), token(tkns)..]
            => unimplemented!(),
        [completion(c), priority(p), completion_date(cod), token(tkns)..]
            => unreachable!(), // should never match, creation_date is greedier
        [completion(c), priority(p), creation_date(crd), token(tkns)..]
            => unimplemented!(),
        // 4 choose 2 = 6
        [creation_date(crd), completion_date(cod), token(tkns)..]
            => unimplemented!(),
        [priority(p), completion_date(cod), token(tkns)..]
            => unreachable!(), // should never match, creation_date is greedier
        [priority(p), creation_date(crd), token(tkns)..]
            => unimplemented!(),
        [completion(c), completion_date(cod), token(tkns)..]
            => unreachable!(), // should never match, creation_date is greedier
        [completion(c), creation_date(crd), token(tkns)..]
            => unimplemented!(),
        [completion(c), priority(p), token(tkns)..]
            => unimplemented!(),
        // 4 choose 1 = 4
        [completion(c), token(tkns)..]
            => unimplemented!(),
        [priority(p), token(tkns)..]
            => unimplemented!(),
        [completion_date(cod), token(tkns)..]
            => unreachable!(), // should never match, creation_date is greedier
        [creation_date(crd), token(tkns)..]
            => unimplemented!(),
        [token(tkns)..]
            => unimplemented!(),
        );

        Ok(tb.build())
    }
}
````
... Phew, and I don't even know if I've missed something
.... is there any easier way to do this? Right now, I am thinking maybe I should do something like:

```rust
    fn todo(node: Node) -> PestResult<Todo> {
        let mut tb = TodoBuilder::default();
        for n into input.into_children() {
            match n.as_rule() {
                "completion" => unimplemented()!,
                "priority" => unimplemented!()!,
                _ => unimplemented!(),
           }
        }
       Ok(tb.build())
    }
```
could `match_nodes!` theoretically support something like:
```rust
 [completion(c)?, priority(p)?, creation_date(crd)?, completion_date(cod)?, token(tkns)..]
            => unimplemented!()!,
```
.. where we get the bindings as `Option`s? 

**PS:** thank you for your help & seasonal greetings! :christmas_tree:

**Comment by Nadrieril** [comment]
> I am a total rust/pest/pest_consume noobie here, so I apologise in advance if I am missing something obvious or if this is not the right channel to ask, feel free to close the issue if that is the case, I won't be offended!

No worries, welcome!

> ```
> todo = { completion? ~ priority? ~ creation_date? ~ completion_date? ~ token* }
> ```

Ah, you've hit an annoying case. In general `match_nodes!` isn't very helpful when there are several "decision points" or "branches" in a single rule. What I usually do is change the grammar, for example by extracting the optional bits into their own rules that each returns an `Option`.
```
maybe_completion = completion?
maybe_priority = priority?
//etc.
todo = { maybe_completion ~ maybe_priority ~ ... }
```
But yeah it's not great.

> Right now, I am thinking maybe I should do something like:
> 
> ```rust
>     fn todo(node: Node) -> PestResult<Todo> {
>         let mut tb = TodoBuilder::default();
>         for n into input.into_children() {
>             match n.as_rule() {
>                 "completion" => unimplemented()!,
>                 "priority" => unimplemented!()!,
>                 _ => unimplemented!(),
>            }
>         }
>        Ok(tb.build())
>     }
> ```

Something like that definitely ought to work. It's probably cleaner than changing the grammar. Let me know if you manage to get it working.

> could `match_nodes!` theoretically support something like:
> 
> ```rust
>  [completion(c)?, priority(p)?, creation_date(crd)?, completion_date(cod)?, token(tkns)..]
>             => unimplemented!()!,
> ```
> 
> .. where we get the bindings as `Option`s?

In theory I think it could, but that would make the macro significantly more complex. Something similar would be to allow `[foo(x).., bar(y)..]`, but that too would be very complex. I see `match_nodes!` as a nice helper; I don't plan to add advanced features to it.

> **PS:** thank you for your help & seasonal greetings! christmas_tree

:heart:

**Comment by vise890** [comment]
> No worries, welcome!

What an amazing community! Everyone is being super helpful, thanks! :heart: 

> Something like that definitely ought to work. It's probably cleaner than changing the grammar. Let me know if you manage to get it working.

I went with this in the end, it's a bit unwrappy, but it should be safe, tests run as before so :shrug: .. 
```rust
     fn todo(node: Node) -> PestResult<Todo> {
        let mut tb = TodoBuilder::default();
        for n in node.into_children() {
            match n.as_rule() {
                Rule::completion => {
                    tb.completed(TodoParser::completion(n).unwrap());
                }
                Rule::priority => {
                    tb.priority(TodoParser::priority(n).unwrap());
                }
                Rule::creation_date => {
                    tb.creation_date(TodoParser::creation_date(n).unwrap());
                }
                Rule::completion_date => {
                    let cod = TodoParser::completion_date(n).unwrap();
                    if !tb.is_completed {
                        log::debug!(
                            "ignoring completion date {:?} for incomplete todo {:?}",
                            cod,
                            tb
                        );
                    } else {
                        tb.completion_date(cod);
                    }
                }
                Rule::token => {
                    tb.push_token(TodoParser::token(n).unwrap());
                }
                _ => unreachable!(),
            }
        }
        Ok(tb.build())
    }
```

> In theory I think it could, but that would make the macro significantly more complex. Something similar would be to allow `[foo(x).., bar(y)..]`, but that too would be very complex. I see `match_nodes!` as a nice helper; I don't plan to add advanced features to it.

I see, well thanks for the library anyway, it has helped me a lot!

**PS:** happy new year!

**Comment by Nadrieril** [comment]
> What an amazing community! Everyone is being super helpful, thanks! :heart:

:blush: 

> it's a bit unwrappy

Why not use `?`? Some of the parsers might fail, for example date parsing might error on a date that doesn't make sense like a 31st of February.

> **PS:** happy new year!

You too!

**Comment by vise890** [comment]
You're totally right of course, thank you!

...I'll have to add some tests on the sad path at some point, but it's still early days in the project
